### ISSUE TITLE
rust library so name can not match as module name?

### ISSUE THREAD

**Issue by oowl** [khvzak/luarocks-build-rust-mlua#3]
in our use case, opendal is Lua module name. opendal build output as `libopendal_lua.so`

So I want to use the rocks build module `opendal`,  For the current  implement, if we want to build module as `opendal`, the backend library name is `libopendal.so` 

Is any work around to implement this?

**Comment by oowl** [comment]
```
╰─$ luarocks make --local           

opendal 0.1.0-1 depends on lua >= 5.1 (5.4-1 provided by VM)
opendal 0.1.0-1 depends on luarocks-build-rust-mlua (0.1.1-1 installed)
    Finished release [optimized] target(s) in 0.12s

Error: Build error: Failed installing ../../target/release/libopendal.so in /home/ouyang/.luarocks/lib/luarocks/rocks-5.4/opendal/0.1.0-1/lib/opendal.so: ../../target/release/libopendal.so: No such file or directory
```

**Comment by khvzak** [comment]
@oowl I crated a PR #4 that should solve this case. Could you take a look

**Comment by khvzak** [comment]
v0.1.2 published
