### ISSUE TITLE
Add --no-default-features

### ISSUE THREAD

**Issue by alerque** [khvzak/luarocks-build-rust-mlua#5]
It would be helpful to me to have `--no-default-features` added to the cargo build commands before adding the custom features. I'm trying to make a repository that compiles a couple of different ways such as a standalone CLI, a Rust Library, or a Lua library. It's a bit hard to manage features if I can't have anything on by default because this build system doesn't have a way to turn them off.

**Comment by alerque** [comment]
It might be good to expand this to just a general purpose way to add flags to the cargo invocation using something in the rockspec. I've setup some workarounds for the feature shenanigans (not ideal but gets my project working) but I'm not having trouble with the `crate-type` business. If I put `cdylib` in the Cargo.toml file using regular Cargo to build a static binary becomes hard, but the Luarocks build of course needs it. I would rather add that bit to the luarocks builder rather than the Cargo project level config, but there doesn't seem to be any mechanism to inject the argument.

**Comment by khvzak** [comment]
Makes sense, I'll make a PR
