### ISSUE TITLE
Building a hybrid rust/lua rock?

### ISSUE THREAD

**Issue by jakesnell** [khvzak/luarocks-build-rust-mlua#6]
I am currently writing bindings for some rust code using mlua, however I am finding it difficult to write the entire module in rust. It would be easier if I could first bind some low-level functions using mlua and rust, and then "patch in" the rest of the functionality with pure lua. Is there a way to do something like this? My understanding is that the "rust-mlua" build type expects to use only the corresponding lib.rs. Should I be calling the lua code directly from the `#[mlua::lua_module]` function that builds up the module table? Thanks in advance for any advice or perspective you can offer!

**Comment by alerque** [comment]
You should be able to achieve this with a setup similar to other Lua Rocks that have a C module plus some Lua module code.

**Comment by jakesnell** [comment]
@alerque Thank you for the suggestion, that does seem useful. Do you happen to know of a sample rock that uses this pattern?

**Comment by jakesnell** [comment]
I ended up solving this by using the `build.install.lua` entry:

```lua
build = {
   type = "rust-mlua",

   install = {
      lua = {
         mymodule = "lua/mymodule.lua"
      }
   },

   modules = {
      "mymodule_core"
   }
}
```

The `mymodule.lua` file can then require from `mymodule_core.so` and build upon it as necessary. Credit to the luarocks gitter for some in-depth suggestions!
